# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NovoTopico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=128)),
                ('user', models.TextField(max_length=24)),
                ('avatar', models.URLField()),
                ('message', models.TextField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(max_length=24)),
                ('avatar', models.URLField()),
                ('message', models.TextField(max_length=1024)),
            ],
        ),
    ]
